name: "Install dependencies"
description: "Install pnpm, nodeJS and dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v3
      with:
        version: 9.4.0

    - name: Cache pnpm modules
      uses: actions/cache@v3.2.6
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
        registry-url: "https://registry.npmjs.org"

    - name: Install dependencies
      run: pnpm -r install --ignore-scripts --frozen-lockfile --strict-peer-dependencies
      shell: bash
