<script>
  import { common } from '@magidoc/plugin-starter-variables'

  const title = common.APP_TITLE.vite.getOrDefault(import.meta.env, 'Magidoc')
</script>

<svelte:head>
  {title} - Welcome
</svelte:head>

<h1>Welcome</h1>
<p>
  Welcome to {title}'s GraphQL API documentation. This documentation was
  automatically generated by
  <a href="https://github.com/magidoc-org/magidoc">Magidoc</a>, a free open
  source static documentation generator for GraphQL.
</p>