<script>
  import { templates } from '@magidoc/plugin-starter-variables'

  const title = templates.APP_TITLE.vite.getOrDefault(
    import.meta.env,
    'Magidoc',
  )
</script>

<svelte:head>
  <title>{title} - Welcome</title>
</svelte:head>

<h1>Welcome</h1>
<p>
  Welcome to {title}'s GraphQL API documentation. This documentation was
  automatically generated by
  <a href="https://github.com/magidoc-org/magidoc">Magidoc</a>, a free open
  source static documentation generator for GraphQL.
</p>
