<script>
  import AppTitle from '$lib/components/common/AppTitle.svelte'
</script>

<h1>Welcome</h1>
<p>
  Welcome to <AppTitle />'s GraphQL API documentation. This documentation was
  automatically generated by
  <a href="https://github.com/magidoc-org/magidoc">Magidoc</a>, a free open
  source static documentation generator for GraphQL. 
</p>
