<script lang="ts" context="module">
  export function load(): LoadOutput {
    const schema = buildClientSchema(
      schemaJson as unknown as IntrospectionQuery,
    )

    const title = templates.APP_TITLE.vite.getOrDefault(
      import.meta.env,
      'Magidoc',
    )

    const pages = formatPages(
      templates.PAGES.vite.getOrDefault(import.meta.env, [
        {
          title: 'Introduction',
          content: [
            {
              title: 'Welcome',
              content: `
              # Welcome

              Welcome to ${title}'s GraphQL API documentation. This documentation was automatically generated by [Magidoc](https://github.com/magidoc-org/magidoc),
              a free open source static documentation generator for GraphQL.
              `
                .split('\n')
                .map((line) => line.trim())
                .join('\n'),
            },
          ],
        },
      ]),
    )

    return {
      stuff: {
        schema,
        content: pages,
      },
      props: {
        schema,
        content: pages,
      },
    }
  }
</script>

<script lang="ts">
  import '../app.css'

  import {
    buildClientSchema,
    GraphQLSchema,
    type IntrospectionQuery,
  } from 'graphql'
  import { Content, Row, Grid, Column } from 'carbon-components-svelte'
  import AppHeader from '$lib/layout/AppHeader.svelte'
  import AppNavigation from '$lib/layout/nav/AppNavigation.svelte'
  import type { LoadOutput } from '@sveltejs/kit/types/internal'
  import schemaJson from '../_schema.json'
  import { templates } from '@magidoc/plugin-starter-variables'
  import { formatPages } from '$lib/pages'
  import type { CustomContent } from 'src/app'

  let isSideNavOpen: boolean

  export let schema: GraphQLSchema

  export let content: CustomContent[]
</script>

<main>
  <AppHeader bind:isSideNavOpen />
  <AppNavigation isOpen={isSideNavOpen} {schema} {content} />

  <Content>
    <Grid>
      <Row>
        <Column>
          <slot />
        </Column>
      </Row>
    </Grid>
  </Content>
</main>
