name: Deploy docs

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Release]
    types:
      - completed

jobs:
  deploy-docs:
    name: Deploy-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/install"
      
      - name: Release Documentation
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.TAG_NAME }}
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "support+actions@github.com"
          git config --global user.name "github-actions-bot"
          pnpm build:plugins && pnpm build:cli && pnpm build:docs && pnpm --filter @magidoc/docs release